import './src/components/main-header/index.js'
import './src/components/animated-button-burger-menu/index.js'
import './src/components/currency-select/index.js'
import './src/components/main-menu/index.js'
import './src/components/product-item/index.js'
import './src/components/product-search-input/index.js'
import './src/components/shadow-area/index.js'
import './src/components/base-slider/index.js'

import './src/features/menu/index.js'
import './src/features/search-product/index.js'
import './src/features/shadow-area/index.js'
